language: objective-c

osx_image: xcode7
xcode_sdk: iphonesimulator9.0

before_install:
    - brew update
    - brew uninstall xctool && brew install --HEAD xctool
install: true

xcode_workspace: Signal.xcworkspace
xcode_scheme: Signal
